### PR TITLE
Order of constructor arguments from balana.xml is kept

### LINKED ISSUE #62: Bug in ConfigurationStore.getArgs - order of arguments missed
I do a PolicyFinderModule with a constructor with 9 arguments. When balana build de configuration it fails because the arguments of my constructor are in bad order. I put it all in correct order in the balana.xml file, but when it parse the configuration, it fails.

I think it's because in the method **org.wso2.balana.ConfigurationStore.getArgs** the arguments are **stored in a Set, instead of a List**. In that point, the order is missed.

This is the code:

```java
private Set getArgs(Node root) {
        Set args = new HashSet();
        NodeList children = root.getChildNodes();

        for (int i = 0; i < children.getLength(); i++) {
            Node child = children.item(i);
            String name = DOMHelper.getLocalName(child);

            if (child.getNodeType() == Node.ELEMENT_NODE) {
                if (name.equals("string")) {
                    args.add(child.getFirstChild().getNodeValue());
                } else if (name.equals("set")) {
                    args.add(getArgs(child));
                } else {
                    throw new IllegalArgumentException("unkown arg type: " + name);
                }
            }
        }

        return args;
    }
```

The problem is that args is a Set, but It must be a List in order to keep the order in the xml.

Can you fix it?

Thanks.

### PR DESCRIPTION
**Pull request by bergerst**
Fixes #62

### CODE REVIEW

**Comment by cdwijayarathna** [comment]
It would be better if you can send a different pr for travis.yms file addition

**Comment by bergerst** [comment]
If I remove the .travis.yml file from the pull request my Travis builds will fail so I cannot remove the commit from the pull request. I will create another pull request only for the travis.yml file.

When merging my pull request just merge the first commit and not the Travis ones.

**Comment by bergerst** [comment]
@cdwijayarathna Done. While we're at it, which Java version should I aim for? I've found out just recently that the feature of

`Set<String> set = new HashSet<>();`

where the template parameters are determined by looking at the template parameters of the variable was introduced in Java 7 and this commit contains such a change.

The existing code looks like Java 5 with lots of old code from SunXACML written in Java 4. I've got one huge pull request in the making where I've updated all Java 4 code from the original SunXACML code to Java 5 to get rid of the hundreds of compiler warnings for Set, Iterator, Map and List without template parameters.

One last question: Should I create issues if I find bugs I've already solved with pull requests or not? In my other active pull request #61 I've found out that XACML 2.0 RequestCtxs get encoded with the wrong XML namespace but I haven't created an issue for that bug.

**Comment by cdwijayarathna** [comment]
I think the future product releases that will use balana will be on Carbon-5 platform and carbon-5 product are mainly aimed for java8. 

You'll have to report bugs for issues that only exist in merged code for master branch. If you have introduced new issues in your PRs, you can fix them in those PRs. Because PRs that introduce bugs will not get merged. Also if you found any bug introduced by you in an unmerged PR, and if you can't fix it, please leave a comment in the PR.

If you found any issues in current master, please report an issue. You can use jira for that.

**Comment by bergerst** [comment]
I was talking about pre-existing bugs in the master branch.

So you prefer JIRA over Github issues? I can't even find a JIRA project specifically for Balana, only for the Identity Server.

**Comment by cdwijayarathna** [comment]
yes, you can use identity server project to report issues in balana.

**Pull request merged**
